name: Cypress Tests

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 10 * * *'
    
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm start
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}