name: Cypress Tests

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 10 * * *'
    
jobs:
  cypress-run:
    runs-on: ubuntu-latest
  
    strategy:
      fail-fast: false 
      matrix:
        containers: [1, 2]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          wait-on: 'http://localhost:3000' 
          record: true
          parallel: false 
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}